notifications:
  slack: zewo:VjyVCCQvTOw9yrbzQysZezD1
os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode7.3
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew update;
        brew install libxml2;
        brew link --force libxml2;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        sudo apt-get -qq update;
        sudo apt-get -y install libxml2-dev;
    fi
install:
  - eval "$(curl -sL https://raw.githubusercontent.com/Zewo/Zewo/5254525d9da56df29346fd76e99529c22034d61d/Scripts/install-swiftenv.sh)"
script:
  - swift build -Xcc -I/usr/include/libxml2 -Xlinker -rpath -Xlinker $(pwd)/.build/debug/
  - swift build --configuration release -Xcc -I/usr/include/libxml2 -Xlinker -rpath -Xlinker $(pwd)/.build/debug/
  - swift test
